name: Pre-Release

on:
  push:
    branches:
      - main



env:
  INPUT_FILENAME: README
  
      
jobs:

  export-release:
    name: Export and Release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create export directories
        run: |
          mkdir export
          mkdir -p doc/img/mermaid

      - name: Compile mermaid diagrams
        uses: pulledtim/compile-mermaid-markdown-action@be7a8a2d42c7b98edbb6e44c43637bfc6725d6d8
        with:
          files: ./${{ env.INPUT_FILENAME }}.md
          output: 'doc/img/mermaid'
        env:
          HIDE_CODEBLOCKS: 1
          ABSOLUTE_IMAGE_LINKS: ""
          OUTPUT_FILE_TYPE: "png"


      - name: Rename export files
        run: |
          tar -czvf export/processes.tar.gz doc/img/mermaid/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: export

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest"
          files: |
            export/processes.tar.gz
          




  
